"""add employee id and manager id cols

Revision ID: 4015e98ead58
Revises: 965afe62f8d2
Create Date: 2025-06-12 22:01:32.225585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '4015e98ead58'
down_revision: Union[str, None] = '965afe62f8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('employee_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.add_column('tasks', sa.Column('manager_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['manager_id'], ['id'])
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'manager_id')
    op.drop_column('tasks', 'employee_id')
    # ### end Alembic commands ###
