"""Create course_employee_contents table

Revision ID: 755b83611af4
Revises: d505cb9bcde4
Create Date: 2025-06-13 14:06:47.661874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import os

from migrations.utils.triggers import apply_sql_files_from_directory, drop_triggers_and_functions_from_directory


# revision identifiers, used by Alembic.
revision: str = '755b83611af4'
down_revision: Union[str, None] = 'd505cb9bcde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

triggers_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'sql', 'triggers', 'create_course_employee_contents_table')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_employee_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'incorrect', 'done', name='contentstatusenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('course_employee_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['public.contents.id'], name=op.f('fk_course_employee_contents_content_id_contents')),
    sa.ForeignKeyConstraint(['course_employee_id'], ['public.course_employees.id'], name=op.f('fk_course_employee_contents_course_employee_id_course_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_employee_contents')),
    sa.UniqueConstraint('course_employee_id', 'content_id', name='uq_course_employee_content'),
    schema='public'
    )
    op.drop_constraint(op.f('fk_comments_content_id_contents'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('fk_comments_user_id_users'), 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_user_id_users'), 'comments', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_comments_content_id_contents'), 'comments', 'contents', ['content_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_contents_task_id_tasks'), 'contents', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_theory_id_theories'), 'contents', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_course_id_courses'), 'contents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contents_course_id_courses'), 'contents', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_contents_theory_id_theories'), 'contents', 'theories', ['theory_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_contents_task_id_tasks'), 'contents', 'tasks', ['task_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('fk_course_employees_employee_id_users'), 'course_employees', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_employees_course_id_courses'), 'course_employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_course_employees_course_id_courses'), 'course_employees', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_course_employees_employee_id_users'), 'course_employees', 'users', ['employee_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_courses_manager_id_users'), 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_courses_manager_id_users'), 'courses', 'users', ['manager_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###

    apply_sql_files_from_directory(triggers_dir)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_courses_manager_id_users'), 'courses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_courses_manager_id_users'), 'courses', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_course_employees_employee_id_users'), 'course_employees', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_employees_course_id_courses'), 'course_employees', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_course_employees_course_id_courses'), 'course_employees', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_course_employees_employee_id_users'), 'course_employees', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_contents_task_id_tasks'), 'contents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_theory_id_theories'), 'contents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_course_id_courses'), 'contents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contents_course_id_courses'), 'contents', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_contents_theory_id_theories'), 'contents', 'theories', ['theory_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_contents_task_id_tasks'), 'contents', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_comments_content_id_contents'), 'comments', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_comments_user_id_users'), 'comments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_user_id_users'), 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_comments_content_id_contents'), 'comments', 'contents', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_table('course_employee_contents', schema='public')
    # ### end Alembic commands ###

    drop_triggers_and_functions_from_directory(triggers_dir)
