"""Create employee_content_statuses table

Revision ID: c6d41c8fda3c
Revises: 946e054cb83c
Create Date: 2025-05-31 20:36:15.042529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d41c8fda3c'
down_revision: Union[str, None] = '946e054cb83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_content_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_employee_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'incorrect', 'done', name='contentstatusenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['public.contents.id'], name=op.f('fk_employee_content_statuses_content_id_contents')),
    sa.ForeignKeyConstraint(['course_employee_id'], ['public.course_employees.id'], name=op.f('fk_employee_content_statuses_course_employee_id_course_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_content_statuses')),
    schema='public'
    )
    op.drop_constraint(op.f('fk_comments_content_id_contents'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('fk_comments_user_id_users'), 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_content_id_contents'), 'comments', 'contents', ['content_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_comments_user_id_users'), 'comments', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_contents_task_id_tasks'), 'contents', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_theory_id_theories'), 'contents', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_course_id_courses'), 'contents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contents_theory_id_theories'), 'contents', 'theories', ['theory_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_contents_course_id_courses'), 'contents', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_contents_task_id_tasks'), 'contents', 'tasks', ['task_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_course_employees_course_id_courses'), 'course_employees', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_employees_employee_id_users'), 'course_employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_course_employees_employee_id_users'), 'course_employees', 'users', ['employee_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_course_employees_course_id_courses'), 'course_employees', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_courses_manager_id_users'), 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_courses_manager_id_users'), 'courses', 'users', ['manager_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_courses_manager_id_users'), 'courses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_courses_manager_id_users'), 'courses', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_course_employees_course_id_courses'), 'course_employees', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_employees_employee_id_users'), 'course_employees', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_course_employees_employee_id_users'), 'course_employees', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_course_employees_course_id_courses'), 'course_employees', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_contents_task_id_tasks'), 'contents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_course_id_courses'), 'contents', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_contents_theory_id_theories'), 'contents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contents_course_id_courses'), 'contents', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_contents_theory_id_theories'), 'contents', 'theories', ['theory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_contents_task_id_tasks'), 'contents', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_comments_user_id_users'), 'comments', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_comments_content_id_contents'), 'comments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_user_id_users'), 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_comments_content_id_contents'), 'comments', 'contents', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_table('employee_content_statuses', schema='public')
    # ### end Alembic commands ###
